apis/urls.py
from django.urls import path
from .views import (
    TopicList,
    SubTopicList,
    RecordList,
    SubRecordList,
    ApiPageView,
    UserList,
)


urlpatterns = [
    path("", ApiPageView.as_view(), name="api"),
    path("topics/", TopicList.as_view(), name="topics_api"),
    path("subtopics/", SubTopicList.as_view(), name="subtopics_api"),
    path("records/", RecordList.as_view(), name="records_api"),
    path("subrecords/", SubRecordList.as_view(), name="subrecords_api"),
    path("users/", UserList.as_view(), name="users_api"),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

urlpatterns = [
    # Django admin
    path("not-admin/", admin.site.urls),
    # User management
    path("accounts/", include("allauth.urls")),
    # Local apps
    path("", include("pages.urls")),
    path("learning/", include("learning.urls")),
    # API
    path("api/v1/", include("apis.urls")),
    path("api-auth/", include("rest_framework.urls")),  # Login Logout
    path("api/v1/dj-rest-auth/", include("dj_rest_auth.urls")),  # Аутентификация
    path(
        "api/v1/dj-rest-auth/registration/", include("dj_rest_auth.registration.urls")
    ),  # Регистрация
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path(
        "api/schema/redoc/",
        SpectacularRedocView.as_view(url_name="schema"),
        name="redoc",
    ),
    path(
        "api/schema/swagger-ui/",
        SpectacularSwaggerView.as_view(url_name="schema"),
        name="swagger-ui",
    ),
    # tinymce editor
    path("tinymce/", include("tinymce.urls")),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [
        path("__debug__/", include(debug_toolbar.urls)),
    ]
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

learning/urls.py
from django.urls import path
from .views import BookListView, BookDetailView, BookNewView
from .views import SearchResultsListView
from .views import TopicListView, RecordListView, RecordDetailView
from .views import TopicNewView, RecordNewView, RecordUpdateView, RecordDeleteView
from .views import SubRecordListView, SubRecordDetailView, SubRecordUpdateView, SubRecordDeleteView
from .views import SubTopicNewView, SubRecordNewView
from .views import RecordFileCreateView, SubRecordFileCreateView


urlpatterns = [
    path('books/', BookListView.as_view(), name='book_list'),
    path('books/<uuid:pk>/', BookDetailView.as_view(), name='book_detail'),
    path('books/new/', BookNewView.as_view(), name='book_new'),

    # Topic-Record
    path('', TopicListView.as_view(), name='topic_list'),  # Страница со списком тем (и не только(books))
    path('topic-<uuid:pk>/', RecordListView.as_view(), name='topic'),  # Список записей темы('topic')
    path('topic-new/', TopicNewView.as_view(), name='topic_new'),  # Новая тема
    path('topic/record-<uuid:pk>/', RecordDetailView.as_view(), name='record'),  # Личная страница записи опред-й темы
    path('topic/record-<uuid:pk>/files', RecordFileCreateView.as_view(), name='record_files'),  # Файлы записи
    path('topic/record-<uuid:pk>/update', RecordUpdateView.as_view(), name='record_update'),  # Страница редактирования записи
    path('topic/record-<uuid:pk>/delete', RecordDeleteView.as_view(), name='record_delete'),  # Страница удаление записи
    path('topic/<uuid:pk>/record-new/', RecordNewView.as_view(), name='record_new'),  # Новая запись опред-й темы (pk)

    # SubTopic-SubRecord
    path('topic/subtopic-<uuid:pk>/', SubRecordListView.as_view(), name = 'subtopic'),  # Список подзаписей (записей подТемы)
    path('topic/<uuid:pk>/subtopic-new/', SubTopicNewView.as_view(), name='subtopic_new'),  # Новая подТема опред-й темы (pk)
    path('topic/subtopic/subrecord-<uuid:pk>/', SubRecordDetailView.as_view(), name='subrecord'),  #  Личная страница записи подТемы
    path('topic/subtopic/subrecord-<uuid:pk>/files/', SubRecordFileCreateView.as_view(), name='subrecord_files'),  # Файлы подЗаписи
    path('topic/subtopic/subrecord-<uuid:pk>/update', SubRecordUpdateView.as_view(), name='subrecord_update'), # Страница редактирования подзаписи
    path('topic/subtopic/subrecord-<uuid:pk>/delete', SubRecordDeleteView.as_view(), name='subrecord_delete'), # Страница удаления подзаписи
    path('topic/subtopic-<uuid:pk>/subrecord-new/', SubRecordNewView.as_view(), name='subrecord_new'),  # Добавление записи подТемы

    path('search/', SearchResultsListView.as_view(), name='search_results'),  # Поиск по книгам (пока что)
]

learning/models.py
import uuid
from django.conf import settings
from django.db import models
from django.urls import reverse
from django.dispatch import receiver
from tinymce.models import HTMLField


ACCESS_PUBLIC = 0
ACCESS_TEACHER = 1
ACCESS_PRIVATE = 2
ACCESS_LEVEL_CHOICES = [
    (ACCESS_PUBLIC, "Все"),
    (ACCESS_TEACHER, "Преподаватели"),
    (ACCESS_PRIVATE, "Только я"),
]


class Book(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField("Название", max_length=200)
    preview = HTMLField("Превью", blank=True)
    text = HTMLField()
    image = models.ImageField("Изображение", upload_to="images/", blank=True)
    document = models.FileField("Документ", upload_to="documents/", blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        indexes = [
            models.Index(fields=["id"], name="id_index"),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("book_detail", args=[str(self.id)])


class Review(models.Model):
    book = models.ForeignKey(
        Book,
        on_delete=models.CASCADE,
        related_name="reviews",
    )
    review = models.CharField(max_length=255)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.review


class Topic(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    title = models.CharField("Название темы", max_length=200)
    access_level = models.IntegerField(
        "Доступ",
        help_text="Кто видит эту тему и имеет к ней доступ",
        choices=ACCESS_LEVEL_CHOICES,
        default=ACCESS_PUBLIC,
    )
    image = models.ImageField("Изображение", upload_to="images/topics", blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    class Meta:
        indexes = [
            models.Index(fields=["id"], name="id_indexT"),
        ]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("topic", args=[str(self.id)])


class SubTopic(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    title = models.CharField("Название подтемы", max_length=200)
    access_level = models.IntegerField(
        "Имеют доступ",
        help_text="Кто видит эту тему и имеет к ней доступ",
        choices=ACCESS_LEVEL_CHOICES,
        default=ACCESS_PUBLIC,
    )
    image = models.ImageField("Изображение", upload_to="images/subtopics", blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("subtopic", args=[str(self.id)])


class Record(models.Model):
    """Информация, изученная пользователем по теме."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    title = models.CharField("Название темы записи", max_length=200)
    preview = HTMLField("Превью", blank=True)
    text = HTMLField("Описание")
    access_level = models.IntegerField(
        "Имеют доступ",
        help_text="Кто видит эту запись и имеет к ней доступ",
        choices=ACCESS_LEVEL_CHOICES,
        default=ACCESS_PUBLIC,
    )
    image = models.ImageField("Изображение", upload_to="images/records", blank=True)
    document = models.FileField("Документ", upload_to="documents/records", blank=True)
    date_added = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        """Возвращает строковое представление модели. До 50 символов"""
        return self.title

    def get_absolute_url(self):
        return reverse("record", args=[str(self.id)])


class ItemBase(models.Model):
    """Абстрактная модель файлов для записей"""
    title = models.CharField(max_length=250, verbose_name="Название")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True

    def __str__(self):
        return self.title

    def render(self):
        return render_to_string(
            f"learning/items/{self._meta.model_name}.html", {"item": self}
        )


class RecordFile(ItemBase):
    record = models.ForeignKey(Record, on_delete=models.CASCADE, verbose_name="Файл", related_name="files")
    file = models.FileField(
        verbose_name="Доп. документ",
        upload_to="documents/records/",
    )


class SubRecord(models.Model):
    """Информация, изученная пользователем по теме."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    subtopic = models.ForeignKey(SubTopic, on_delete=models.CASCADE)  # subtopic
    title = models.CharField("Название темы записи", max_length=200)
    preview = HTMLField("Превью", blank=True)
    text = HTMLField("Описание")
    access_level = models.IntegerField(
        "Имеют доступ",
        help_text="Кто видит эту запись и имеет к ней доступ",
        choices=ACCESS_LEVEL_CHOICES,
        default=ACCESS_PUBLIC,
    )
    image = models.ImageField("Изображение", upload_to="images/subrecords", blank=True)
    document = models.FileField(
        "Документ", upload_to="documents/subrecords", blank=True
    )
    date_added = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        """Возвращает строковое представление модели. До 50 символов"""
        return self.title

    def get_absolute_url(self):
        return reverse("subrecord", args=[str(self.id)])


class SubRecordFile(ItemBase):
    subrecord = models.ForeignKey(
        SubRecord, on_delete=models.CASCADE, verbose_name="Файл", related_name="files"
    )
    file = models.FileField(
        verbose_name="Доп. документ",
        upload_to="documents/subrecords",
    )

learning/forms.py
from django import forms
from .models import Book, Topic, Record, SubTopic, SubRecord
from tinymce.widgets import TinyMCE


class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        fields = '__all__'
        widgets = {
            'text': TinyMCE(attrs={'cols': 80, 'rows': 30}),
            'preview': TinyMCE(attrs={'cols': 80, 'rows': 10}),
        }

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ('title', 'access_level')


class SubTopicForm(forms.ModelForm):
    class Meta:
        model = SubTopic
        fields = ('title', 'access_level')


class RecordForm(forms.ModelForm):
    class Meta:
        model = Record
        fields = ('title', 'preview', 'text', 'access_level', 'image', 'document')
        widgets = {
            'text': TinyMCE(attrs={'cols': 80, 'rows': 30}),
            'preview': TinyMCE(attrs={'cols':80, 'rows': 30}),
        }


class SubRecordForm(forms.ModelForm):
    class Meta:
        model = SubRecord
        fields = ('title', 'preview', 'text', 'access_level', 'image', 'document')
        widgets = {
            'text': TinyMCE(attrs={'cols': 80, 'rows': 30}),
            'preview': TinyMCE(attrs={'cols':80, 'rows': 30}),
        }

templates/learning/book_new.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}New Book{% endblock title %}

{% block content %}
    <head>
        {{ form.media }}
    </head>
    <h1>Добавление:</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">Создать</button>
    </form>
{% endblock content %}

templates/learning/record_delete.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Удаление записи "{{ record }}"{% endblock title %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="alert alert-danger" role="alert">
            <p>Вы действительно хотите удалить запись "{{ record }}"?</p>
            {{ form|crispy }}
            <button class="btn btn-primary" type="Confirm">Удалить</button>
        </div>
    </form>
{% endblock content %}
<input type="submit" value="Confirm">

templates/learning/record_detail.html
{% extends '_base.html' %}
{% load has_group %}

{% block title %}{{ record }}{% endblock title %}

{% block content %}

    {# FOUR COLUMN IN THE TOP #}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <p><i class="bi bi-tag-fill"></i> Тема: <a href="{% url 'topic' record.topic_id %}">{{ record.topic }}</a></p>
            </div>
            <div class="col-md-3">
                <a><i class="bi bi-calendar-date"></i> Дата: {{ record.date_added }}</a>
            </div>
            <div class="col-md-3">
                {% if request.user|has_group:'teachers' %}
                    {% if record.access_level == 1 %}
                        <a><i class="bi bi-people-fill"></i> Доступ: Преподаватели </a>
                    {% endif %}
                    {% if record.access_level == 2 %}
                        <a><i class="bi bi-person-fill"></i> Доступ: Только я</a>
                    {% endif %}
                    {% if record.access_level == 0 %}
                        <a><i class="bi bi-people"></i> Доступ: Все</a>
                    {% endif %}
                {% endif %}
            </div>
            <div class="col-md-3">
                {% if request.user|has_group:'teachers' or record.author == request.user %}
                    <a href="{% url 'record_update' record.pk %}" class="badge badge-primary"><i class="bi bi-gear"></i>  Редактировать</a>
                    <a href="{% url 'record_files' record.pk %}" class="badge badge-primary"><i class="bi bi-filetype-docx"></i>  Добавить документы</a>
                    <a href="{% url 'record_delete' record.pk %}" class="badge badge-danger"><i class="bi bi-trash3"></i>  Удалить</a>
                {% endif %}
            </div>
        </div>

        {# SIDEBAR col-md-3 #}
        <div class="row">
            <div class="col-md-3">
                  <div class="list-group">
                      <a href="{% url 'home' %}" class="list-group-item list-group-item-action"> Главная</a>
                      <a href="{% url 'topic_list' %}" class="list-group-item list-group-item-action"> Обучение</a>
                      <a href="{% url 'topic' record.topic_id %}" class="list-group-item list-group-item-action"> {{ record.topic }} </a>
                      <a class="list-group-item list-group-item-action" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">> По этой теме </a>
                      <div class="collapse show" id="collapseExample">
                        <div class="card card-body">
                            {% for r in record_list %}
                                {% if record == r %}
                                    <li><a href="{{ r.get_absulute_url }}" class="sidefont"> <b>{{ r }}</b> </a></li>
                                {% else %}
                                    <li><a href="{{ r.get_absolute_url }}" class="sidefont"> {{ r }} </a></li>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                  </div>
            </div>

            {# MAIN CONTENT record_list col-md-9 #}
            <div class="col-md-9">
                <h2><a href="">{{ record.title }}</a></h2>
                {% if record.image %}
                    <img class="bookcover" src="{{ record.image.url }}" alt="{{ record.title }}">
                {% endif %}
                <p>{{ record.text|safe }}</p>

                {# Documents #}
                {% if record.document %}
                  <div class="card">
                    <div class="card-body">
                      <div class="row align-items-center">
                        <div class="col-auto pr-0">
                          <i class="bi bi-file-earmark-text h2 text-muted mb-0"></i>
                        </div>
                        <div class="col">
                          <h5 class="card-title mb-1">{{ record.document.name }}</h5>
                          <p class="card-text mb-0"><small class="text-muted">{{ record.document.size|filesizeformat }}</small></p>
                          <p class="card-text mb-0"><small class="text-muted">{{ record.document.created }}</small></p>
                          <a href="{{ record.document.url }}" class="btn btn-sm btn-primary mt-2"><i class="bi bi-download"></i> Скачать</a>
                        </div>
                      </div>
                    </div>
                  </div>
                {% endif %}

                {% for f in record.files.all %}
                  <div class="card mt-3">
                    <div class="card-body">
                      <div class="row align-items-center">
                        <div class="col-auto pr-0">
                          <i class="bi bi-file-earmark h2 text-muted mb-0"></i>
                        </div>
                        <div class="col">
                          <h5 class="card-title mb-1">{{ f.title }}</h5>
                          <p class="card-text mb-0"><small class="text-muted">{{ f.file.size|filesizeformat }}</small></p>
                          <p class="card-text mb-0"><small class="text-muted">{{ f.created }}</small></p>
                          <a href="{{ f.file.url }}" class="btn btn-sm btn-primary mt-2"><i class="bi bi-download"></i> Скачать</a>
                        </div>
                      </div>
                    </div>
                  </div>
                {% endfor %}

            </div>
        </div>
    </div>

{% endblock content %}

templates/learning/record_file_formset.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}
  Файлы для {{ record.title }}
{% endblock title %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="{{ record.topic.get_absolute_url }}">{{ record.topic }}</a></li>
    <li class="breadcrumb-item"><a href="{{ record.get_absolute_url }}"> {{ record.title }}</a></li>
    <li class="breadcrumb-item active" aria-current="page"> Добавление документов</li>
  </ol>
</nav>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">Тема: {{ record.topic }}</h5>
    <h6 class="card-subtitle mb-2 text-muted">Запись: {{ record.title }}</h6>
    <p class="card-text">Дата добавления записи: {{ record.date_added }}</p>
  </div>
</div>

<div class="card mt-3">
  <div class="card-header">
    Добавление документов
  </div>
  <div class="card-body">
    <form method="post" enctype="multipart/form-data">
      {% csrf_token %}
      {{ formset|crispy }}

      <button class="btn btn-primary" type="submit">
        <i class="bi bi-cloud-upload"></i> Добавить файлы
      </button>
    </form>
  </div>
</div>
{% endblock content %}

templates/learning/record_new.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Новая запись{% endblock title %}

{% block content %}
    <head>
        {{ form.media }}
    </head>
    <h1>Добавление:</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">Создать</button>
    </form>
{% endblock content %}

action="{% url 'record_new' %}"

templates/learning/record_update.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Редактирование записи "{{ record }}"{% endblock title %}

{% block content %}
    <head>
        {{ form.media }}
    </head>
    <h1>Редактирование:</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-success" type="submit">Сохранить</button>
    </form>
{% endblock content %}

templates/learning/search_results.html
{% extends '_base.html' %}

{% block title %}Поиск{% endblock title%}

{% block content %}
    <h1>Результаты поиска</h1>

    {% for object in topic_list %}
        <div>
            <h3><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h3>
            <p>{{ object.date_added }}</p>
        </div>
    {% endfor %}

    {% for object in record_list %}
        <div>
            <h3><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h3>
            <p>{{ object.date_added }}</p>
        </div>
    {% endfor %}

    {% for object in subtopic_list %}
        <div>
            <h3><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h3>
            <p>{{ object.date_added }}</p>
        </div>
    {% endfor %}

    {% for object in subrecord_list %}
        <div>
            <h3><a href="{{ object.get_absolute_url }}">{{ object.title }}</a></h3>
            <p>{{ object.date_added }}</p>
        </div>
    {% endfor %}

{% endblock content %}

templates/learning/subrecord_delete.html
{% extends '_base.html' %}
{% load crispy_forms_tags %}

{% block title %}Удаление записи "{{ subrecord }}" {% endblock title %}
{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="alert alert-danger" role="alert">
            <p>Вы действительно хотите удалить запись "{{ subrecord }}"?</p>
            {{ form|crispy }}
            <button class="btn btn-primary" type="Confirm">Удалить</button>
        </div>
    </form>
{% endblock content %}
<input type="submit" value="Confirm">

templates/learning/subrecord_detail.html
{% extends '_base.html' %}
{% load has_group %}

{% block title %}{{ subrecord }}{% endblock title %}

{% block content %}

    {# FOUR COLUMN IN THE TOP #}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-3">
                <p><i class="bi bi-tag-fill"></i> Подтема: <a href="{% url 'subtopic' subrecord.subtopic_id %}" class="">{{ subrecord.subtopic }}</a></p>
            </div>
            <div class="col-md-3">
                <p><a><i class="bi bi-calendar-date"></i> Дата: {{ subrecord.date_added }}</a></p>
            </div>
            <div class="col-md-3">
                {% if request.user|has_group:'teachers' %}
                    {% if subrecord.access_level == 1 %}
                        <a><i class="bi bi-people-fill"></i> Доступ: Преподаватели </a>
                    {% endif %}
                    {% if subrecord.access_level == 2 %}
                        <a><i class="bi bi-person-fill"></i> Доступ: Только я</a>
                    {% endif %}
                    {% if subrecord.access_level == 0 %}
                        <a><i class="bi bi-people"></i> Доступ: Все</a>
                    {% endif %}
                {% endif %}
            </div>
            <div class="col-md-3">
                {% if request.user|has_group:'teachers' or subrecord.author == request.user %}
                    <a href="{% url 'subrecord_update' subrecord.pk %}" class="badge badge-primary"><i class="bi bi-gear"></i>  Редактировать</a>
                    <a href="{% url 'subrecord_files' subrecord.pk %}" class="badge badge-primary"><i class="bi bi-filetype-docx"></i>  Добавить документы</a>
                    <a href="{% url 'subrecord_delete' subrecord.pk %}" class="badge badge-danger"><i class="bi bi-trash3"></i>  Удалить</a>
                {% endif %}
            </div>
        </div>

        {# SIDEBAR col-md-3 #}
         <div class="row">
            <div class="col-md-3">
                  <div class="list-group">
                      <a href="{% url 'home' %}" class="list-group-item list-group-item-action"> Главная</a>
                      <a href="{% url 'topic_list' %}" class="list-group-item list-group-item-action"> Обучение</a>
                      <a href="{% url 'subtopic' subrecord.subtopic_id %}" class="list-group-item list-group-item-action"> {{ subrecord.subtopic }}</a>
                      <a class="list-group-item list-group-item-action" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">> По этой теме </a>
                      <div class="collapse show" id="collapseExample">
                        <div class="card card-body">
                            {% for r in subrecord_list %}
                                {% if subrecord == r %}
                                    <li><a href="{{ r.get_absulute_url }}" class="sidefont"> <b>{{ r }}</b> </a></li>
                                {% else %}
                                    <li><a href="{{ r.get_absolute_url }}" class="sidefont"> {{ r }} </a></li>
                                {% endif %}
                            {% endfor %}
                        </div>
                    </div>
                  </div>
            </div>

            {# MAIN CONTENT record_list col-md-9 #}
            <div class="col-md-9">
                <h2><a href="">{{ subrecord.title }}</a></h2>
                {% if subrecord.image %}
                    <img class="bookcover" src="{{ subrecord.image.url }}" alt="{{ subrecord.title }}">
                {% endif %}
                <p>{{ subrecord.text|safe }}</p>
                {% if subrecord.document %}
                  <div class="card">
                    <div class="card-body">
                      <div class="row align-items-center">
                        <div class="col-auto pr-0">
                          <i class="bi bi-file-earmark-text h2 text-muted mb-0"></i>
                        </div>
                        <div class="col">
                          <h5 class="card-title mb-1">{{ subrecord.document.name }}</h5>
                          <p class="card-text mb-0"><small class="text-muted">{{ subrecord.document.size|filesizeformat }}</small></p>
                          <p class="card-text mb-0"><small class="text-muted">{{ subrecord.document.created }}</small></p>
                          <a href="{{ subrecord.document.url }}" class="btn btn-sm btn-primary mt-2"><i class="bi bi-download"></i> Скачать</a>
                        </div>
                      </div>
                    </div>
                  </div>
                {% endif %}

                {% for f in subrecord.files.all %}
                  <div class="card mt-3">
                    <div class="card-body">
                      <div class="row align-items-center">
                        <div class="col-auto pr-0">
                          <i class="bi bi-file-earmark h2 text-muted mb-0"></i>
                        </div>
                        <div class="col">
                          <h5 class="card-title mb-1">{{ f.title }}</h5>
                          <p class="card-text mb-0"><small class="text-muted">{{ f.file.size|filesizeformat }}</small></p>
                          <p class="card-text mb-0"><small class="text-muted">{{ f.created }}</small></p>
                          <a href="{{ f.file.url }}" class="btn btn-sm btn-primary mt-2"><i class="bi bi-download"></i> Скачать</a>
                        </div>
                      </div>
                    </div>
                  </div>
                {% endfor %}

            </div>
        </div>
    </div>

{% endblock content %}

    <a href="{% url 'topic_list' %}" class="">Обучение</a> >
    <a href="{% url 'topic' subrecord.subtopic.topic_id  %}" class="">{{ subrecord.subtopic.topic }}</a> >
    <a href="{% url 'subtopic' subrecord.subtopic_id  %}" class="">{{ subrecord.subtopic }}</a> >
    <a href="{% url 'subrecord' subrecord.id %}" class="">{{ subrecord }}</a>